Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fidp = fiducial_points(ppg_filt,ibis,fs,vis = True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [12][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m fidp [38;5;241m=[39m [43mfiducial_points[49m[43m([49m[43mppg_filt[49m[43m,[49m[43mibis[49m[43m,[49m[43mfs[49m[43m,[49m[43mvis[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m

Input [0;32mIn [11][0m, in [0;36mfiducial_points[0;34m(x, pks, fs, vis)[0m
[1;32m     67[0m start [38;5;241m=[39m ons[i]
[1;32m     68[0m stop [38;5;241m=[39m ons[i [38;5;241m+[39m [38;5;241m1[39m]
[0;32m---> 69[0m ind_pks, [38;5;241m=[39m np[38;5;241m.[39mintersect1d(np[38;5;241m.[39mwhere(pks [38;5;241m<[39m stop), np[38;5;241m.[39mwhere(pks [38;5;241m>[39m start))
[1;32m     70[0m ind_pks [38;5;241m=[39m pks[ind_pks]
[1;32m     71[0m ibi_portion [38;5;241m=[39m x[ind_pks:stop]

[0;31mValueError[0m: not enough values to unpack (expected 1, got 0)
ValueError: not enough values to unpack (expected 1, got 0)

